slots: 
  movie.name:
    type: text
  movie.genre:
    type: text
  movie.release_region:
    type: text
  movie.release_date:
    type: float
  movie.language:
    type: text
  movie.location:
    type: text
  actor.name:
    type: text
  director.name:
    type: text
  movie.budget:
    type: float
  movie.duration:
    type: text
  movie.gross_revenue:
    type: float
  language:
    type: text
  color:
    type: bool
  country.name:
    type: text
  plot_keywords:
    type: list
  movie.star_rating:
    type: float
  likes:
    type: float


entities:
  - actor.name
  #- actor.nationality
  #- actor.type
  #- award.category
  #- award.ceremony
  #- character.name
  - country.name
  - director.name
  #- director.nationality
  #- movie.description
  - movie.genre
  - movie.gross_revenue
  - movie.language
  - movie.location
  - movie.name
  - movie.release_date
  - movie.release_region
  - movie.star_rating
  #- movie.subject
  #- person.name
  #- person.nationality
  #- producer.name
  #- rating.name

## the commented ones are either not considered or omitted for data absence
intents:
 - greet
 - affirm
 - deny
 - inform
 - goodbye
 - thankyou
 - request_info
 - actor_name
 #- actor_name_&&_character
 #- award
 #- award_category_count
 #- award_ceremony_&&_award_category
 #- award_count
 #- birth_date
 - budget
 #- character
 #- composer
 - country
 - director_name
 - director_&&_movie_&&_date_&&_star_rating
 - director_&&_movie_&&_star_rating
 - director_&&_movie_name
 #- director_&&_producer
 - genre
 - language
 #- media
 - movie
 - movie_&&_budget
 - movie_&&_date
 - movie_&&_director
 - movie_&&_language
 #- movie_&&_media
 #- movie_&&_producer
 - movie_&&_rating
 #- movie_&&_revenue
 #- movie_&&_star_rating
 #- movie_&&_subjects
 #- movie_&&_trailer
 - movie_count
 - movie_name
 #- movie_other
 #- organization
 #- other
 #- person
 #- person_name
 #- picture
 #- producer
 #- producer_&&_picture
 #- producer_&&_producer
 #- producer_count
 - rating
 #- rating_&&_star_rating
 - release_date
 #- revenue
 #- review
 #- review_&&_movie
 #- review_&&_rating
 - runtime
 - star_rating
 #- subjects
 #- synopsis
 #- theater
 #- trailer
 #- writer 


templates:
  utter_greet:
    - "Good Morning Sir/Miss"
  utter_goodbye:
    - "Farewell"
    - "May you have a pleasent day, farewell!"
  utter_default:
    - "default message"
  utter_ack_dosearch: 
    - "Request sheduled, let me check my slots"
  utter_ack_findalternatives:
    - "Oh it is not what you requested? Pardon, let me check again my database"
  utter_ask_howcanhelp:
    - "how can I help you?"
    - "May I be of some help?"
  utter_ask_morethanone:
    - "My search highlighted more than one result, which one do you prefer?"
  utter_ask_moreupdates: 
    - "May I provide you more information?"
  utter_ask_cantdoit:
    - "Apologize Sir/Miss, I can not help you"


# bot's actions
actions:
- utter_greet
- utter_goodbye
- utter_default
- utter_ack_dosearch
- utter_ack_findalternatives
- utter_ask_howcanhelp
- utter_ask_morethanone
- utter_ask_moreupdates
- utter_ask_cantdoit
### more actions
- actions.ActionRestarted
- actions.ActionAllSlotReset
- actions.ActionMovie
- actions.ActionActor
- actions.ActionDirector
- actions.ActionGenre
- actions.ActionCountry
- actions.ActionYear
- actions.ActionLanguage
- actions.ActionDuration
- actions.ActionBudget
- actions.ActionScore
- actions.ActionLike


